### ISSUE TITLE
Properties panel

### ISSUE THREAD

**Issue by asad11111** [narve/angular-bpmn#10]
Hi narve. I hope you are doing good. Can we have an extended properties panel as shown in the url. e.g when we click on an element. There is input /output tap shown in the properties panel https://raw.githubusercontent.com/bpmn-io/bpmn-js-examples/master/properties-panel/docs/screenshot.png.

**Comment by narve** [comment]
Not sure what you are referring to. It is absolutely possible to have more than one panel in the properties panel, and to specify your own property panel / property groups / properties. I believe the project as it is already has a custom property?
