### ISSUE TITLE
cant save and load work from locally

### ISSUE THREAD

**Issue by AbdurRehman91** [narve/angular-bpmn#11]
Hi.i am running the project on locally.currently i am unable to load the saved work on the project and also could not able to save the work on my computer using the file extension .bpmn .As i am going through the documentation,i have found out that there is a file cycle of saving the xml doc.but its implementation is not present in angular code.The life cycle is following:
 * saveXML.start (before serialization)
 * saveXML.serialized (after xml generation)
 * saveXML.done (everything done)
I am assuming the working to be similar as https://demo.bpmn.io where users can save and load the work

Thanks

**Comment by AbdurRehman91** [comment]
Kindly reply to this issue as i am waiting to hearing from you guys back 
thanks

**Comment by narve** [comment]
Hi there. The project, as it is, supports exporting the XML version of the business process as a string, printing it in the console.

Saving locally is a totally different issue, and so is sending it to a server. How to do this depends on what you are building, and is NOT provided by this demo project at all.
