### ISSUE TITLE
Hiding the default tools in palette present in angular-app

### ISSUE THREAD

**Issue by AbdurRehman91** [narve/angular-bpmn#12]
Hi.currently i am going trying to customize the palette in angular app in a way that i can hide/block the default tools from the palette.For example 'lasso-tools','hands tools' etc.In the bpmn example given in JS [here](https://github.com/bpmn-io/bpmn-js-examples/tree/master/custom-elements) it is fully possible by using the following code 

`function PaletteProvider(palette, create, elementFactory, spaceTool, lassoTool, handTool, translate) {

  this._palette = palette;
  this._create = create;
  this._elementFactory = elementFactory;
  this._spaceTool = spaceTool;
  this._lassoTool = lassoTool;
  this._handTool = handTool;
  this._translate = translate;

  palette.registerProvider(this);
}
`
at first and then  in function **getPaletteEntries** we can  just simply provide the list of actions/tools we want in palette in **assign** function.
But now currently in angular app we are inheriting the class **IPaletteProvider** as i am figuring out rest of methods.
Any help in this regard is highly appreciated

thanks

**Comment by narve** [comment]
Due to the method PaletteProvider works, it is not very simple. 

You could copy PaletteProvider.js from bpmn-js/lib/features/palette, modify it, and then use your new file instead of `import _PaletteProvider from 'bpmn-js/lib/features/palette/PaletteProvider';

**Comment by narve** [comment]
However, the extremely simple way is to just hide the buttons you want to remove, by adding e.g. these lines in styles.scss: 

```
div.bpmn-icon-start-event-none {
  display:none;
}
```
