### ISSUE TITLE
Customizing palette

### ISSUE THREAD

**Issue by mytran22** [narve/angular-bpmn#13]
I need to add an icon to palette and assign a custom behaviour to that icon.

For that purpose I edited CustomPaletteProvider.ts and added a part from bpmn-js-nyan package (https://github.com/bpmn-io/bpmn-js-nyan/blob/master/lib/nyan/palette/NyanPaletteProvider.js)

With my code I can see a new element is already added to palette. But I can't set a baheviour to that item.
My version below this post.

```
import {IPalette, IPaletteProvider} from "../bpmn-js/bpmn-js";

export class CustomPaletteProvider implements IPaletteProvider {

  static $inject = ['palette', 'originalPaletteProvider'];

  myElementFactory;
  myCreate;

  // Note that names of arguments must match injected modules, see InjectionNames.
  // I don't know why originalPaletteProvider matters but it breaks if it isn't there.
  // I guess since this component is injected, and it requires an instance of originalPaletteProvider,
  // originalPaletteProvider will be new'ed and thus call palette.registerProvider for itself.
  // There probably is a better way.
  constructor(private palette: IPalette, private originalPaletteProvider: IPaletteProvider) {
    // console.log(this.constructor.name, "constructing", palette, originalPaletteProvider);
    palette.registerProvider(this);
	
    this.myElementFactory = originalPaletteProvider._elementFactory;
    this.myCreate = originalPaletteProvider._create;
 }

  getPaletteEntries() {

    function startCreate(event) {
      var serviceTaskShape = this.myElementFactory.create(
          'shape', { type: 'bpmn:ServiceTask' }
      );

      this.myCreate.start(event, serviceTaskShape);
    }


    return {
      save: {
        group: 'tools',
        className: ['fa-save', 'fa'],
        title: 'TEST',
        action: {
          click: () => console.log( 'TEST Action clicked!')
        }
      },
      createservicetask: {
        group: 'tools',
        title: 'TEST3',
        className: ['bpmn-icon-start-event-signal'],
        action: {
          dragstart: startCreate,
          click: startCreate
        }
    }
    };
  }
}
```

**Comment by mytran22** [comment]
Is it not possible to add a behaviour to a custom element ?

**Comment by mytran22** [comment]
Yes it is a bpmn.io problem, but none of the other projects seemed to approximate to my requirements.
Your solution nearly makes it except setting a custom function on click of the button.

**Comment by mytran22** [comment]
It seems like CustomPaletteProvider can't access to elementFactory.
https://github.com/narve/angular-bpmn/blob/master/src/app/props-provider/CustomPaletteProvider.ts

In CustomPalette.js elementFactory is included in constructor.
https://github.com/bpmn-io/bpmn-js-examples/blob/master/custom-elements/app/custom-modeler/custom/CustomPalette.js

**Comment by narve** [comment]
I just checked that we can include elementFactory in the constructor, see commit ea066dc8319067967321fb8ba8fb310c4c9cb798
