### ISSUE TITLE
Getting error on ng build --prod

### ISSUE THREAD

**Issue by lalithkumarachanta** [narve/angular-bpmn#6]
im getting the error when doing ng build --prod, the problem with propertiesPanel custom providers. Can i know how can i resolve the issue. I think the issue with minification for properties panel.js file

Erro - Error: No provider for "l"! (Resolving: propertiesPanel -> propertiesProvider -> l)

**Comment by andrasczeh** [comment]
you have to provide the names for injection: https://forum.bpmn.io/t/angular-5-cli-based-bpmn-project-now-on-github/2190/13
In both custom providers you should add inside the class: 
`static $inject = ['translate', 'bpmnPropertiesProvider' ...];`

**Comment by lalithkumarachanta** [comment]
@andrasczeh , i was added the below line in customPropertiesProvider
static injector=['translate',"elementRegistry","eventBus","bpmnFactory","bpmnPropertiesProvider"];
and
static inject=['translate',"elementRegistry","eventBus","bpmnFactory","bpmnPropertiesProvider"];
but still get the same error on ng build - prod.

Correct me if im doing anything wrong.

**Comment by lalithkumarachanta** [comment]
@andrasczeh ,

Thank you.. Its working now ng build -prod too. Now i was able to customize the General tabs data. Thanks once again.

**Comment by narve** [comment]
Sorry for the late reply, folks! For some reason I wasn't 'watch'-ing this repo so I did not get any notifications from Github. 

I reproduced the problem but the code @andrasczeh mentioned didn't work for me. I use Windows+Powershell. 

Can one of you (@andrasczeh, @lalithkumarachanta) provide a pull request and/or code samples, including build environment?

**Comment by narve** [comment]
Never mind, some local computer problems. Your fix worked, thanks :)
